FROM confluentinc/cp-kafka:latest

# Copy the Kafka topic creation script into the container
COPY create-kafka-topic.sh /tmp/create-kafka-topic.sh

# Give execute permissions to the script
RUN chmod +x /tmp/create-kafka-topic.sh

# Run Kafka with the script to create the topic
CMD ["/bin/bash", "/tmp/create-kafka-topic.sh"]